name: "Build and Create Prerelease"

on:
  push:
    branches:
      - master

env:
  DEPENDENCIES: libusb-1.0-0-dev libudev-dev gcovr cmake doxygen

jobs:
  coverage:
    name: Generate Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install $DEPENDENCIES
        shell: bash
      - name: Run CMake
        run: cd "${{ runner.temp }}" && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug "${{ github.workspace }}"
      - name: Generate coverage
        run: cd "${{ runner.temp }}" && make coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Code_Coverage_Report
          path: "${{ runner.temp }}/coverage"
  docs:
    name: Generate Doxygen Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install $DEPENDENCIES
        shell: bash
      - name: Run CMake
        run: cd "${{ runner.temp }}" && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug "${{ github.workspace }}"
      - name: Generate docs
        run: cd "${{ runner.temp }}" && make doxygen
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: Doxygen_Docs
          path: "${{ runner.temp }}/html"
  publish-artifacts:
    name: Upload Artifacts to Project Page
    runs-on: ubuntu-latest
    needs: [coverage, docs]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Move files
        run: |
          rm -rf docs coverage
          mv Doxygen_Docs docs
          mv Code_Coverage_Report coverage
        shell: bash
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: '["docs", "coverage"]'
          default_author: github_actions
          message: "Commit updated coverage and docs"
  build-static:
    name: Build Static Library Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install $DEPENDENCIES
        shell: bash
      - name: Generate buildfiles
        run: cd "${{ runner.temp }}" && cmake -G "Unix Makefiles" -DBLINK1_LIB_BUILD_STATIC=ON "${{ github.workspace }}"
      - name: Build library
        run: cd "${{ runner.temp }}" && make
      - name: Run tests
        run: cd "${{ runner.temp }}" && make test
      - name: Upload library files
        uses: actions/upload-artifact@v3
        with:
          name: Static Libraries
          path: "${{ runner.temp }}/lib*.a"
  build-shared:
    name: Build Shared Library Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install $DEPENDENCIES
        shell: bash
      - name: Generate buildfiles
        run: cd "${{ runner.temp }}" && cmake -G "Unix Makefiles" -DBLINK1_LIB_BUILD_SHARED=ON "${{ github.workspace }}"
      - name: Build library
        run: cd "${{ runner.temp }}" && make
      - name: Run tests
        run: cd "${{ runner.temp }}" && make test
      - name: Upload library files
        uses: actions/upload-artifact@v3
        with:
          name: Static Libraries
          path: "${{ runner.temp }}/lib*.so"
  upload-headers:
    name: Upload Header Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload headers
        uses: actions/upload-artifact@v3
        with:
          name: Header Files
          path: "${{ github.workspace }}/include"

