name: build

on:
  push:
    branches:
      - master

env:
  DEPENDENCIES: libusb-1.0-0-dev libudev-dev gcovr cmake doxygen

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install $DEPENDENCIES
        shell: bash
      - name: Run CMake
        run: cd "${{ runner.temp }}" && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug "${{ github.workspace }}"
      - name: Generate coverage
        run: cd "${{ runner.temp }}" && make coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Code_Coverage_Report
          path: "${{ runner.temp }}/coverage"
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install $DEPENDENCIES
        shell: bash
      - name: Run CMake
        run: cd "${{ runner.temp }}" && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug "${{ github.workspace }}"
      - name: Generate docs
        run: cd "${{ runner.temp }}" && make doxygen
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: Doxygen_Docs
          path: "${{ runner.temp }}/html"
  publish-artifacts:
    runs-on: ubuntu-latest
    needs: [coverage, docs]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Move files
        run: |
          rm -rf docs coverage
          mv Doxygen_Docs docs
          mv Code_Coverage_Report coverage
        shell: bash
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: '["docs", "coverage"]'
          default_author: github_actions
          message: "Commit updated coverage and docs"


